apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"prometheus","namespace":"microservices"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"prometheus"}},"template":{"metadata":{"labels":{"app":"prometheus"}},"spec":{"containers":[{"args":["--config.file=/etc/prometheus/prometheus.yml","--storage.tsdb.path=/prometheus","--web.console.libraries=/etc/prometheus/console_libraries","--web.console.templates=/etc/prometheus/consoles","--storage.tsdb.retention.time=200h","--web.enable-lifecycle"],"image":"prom/prometheus:latest","name":"prometheus","ports":[{"containerPort":9090}],"volumeMounts":[{"mountPath":"/prometheus","name":"prometheus-storage"},{"mountPath":"/etc/prometheus","name":"prometheus-config"}]}],"volumes":[{"emptyDir":{},"name":"prometheus-storage"},{"configMap":{"name":"prometheus-config"},"name":"prometheus-config"}]}}}}
  creationTimestamp: "2025-09-09T01:56:23Z"
  generation: 4
  name: prometheus
  namespace: microservices
  resourceVersion: "310637"
  uid: 2d6e3e5e-e304-4315-974f-c7413a95d1fc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
    spec:
      containers:
      - args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.console.templates=/etc/prometheus/consoles
        - --storage.tsdb.retention.time=200h
        - --web.enable-lifecycle
        - --rules.file=/etc/prometheus/rules/alert_rules.yml
        image: prom/prometheus:latest
        imagePullPolicy: Always
        name: prometheus
        ports:
        - containerPort: 9090
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/rules
          name: prometheus-rules
        - mountPath: /prometheus
          name: prometheus-storage
        - mountPath: /etc/prometheus
          name: prometheus-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-rules
        name: prometheus-rules
      - emptyDir: {}
        name: prometheus-storage
      - configMap:
          defaultMode: 420
          name: prometheus-config
        name: prometheus-config
status:
  conditions:
  - lastTransitionTime: "2025-09-09T01:56:23Z"
    lastUpdateTime: "2025-09-10T08:41:52Z"
    message: ReplicaSet "prometheus-688994dfdf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-09-10T08:42:22Z"
    lastUpdateTime: "2025-09-10T08:42:22Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 4
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
