apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: php:8.1-apache
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args:
          - |
            docker-php-ext-install pdo pdo_mysql mysqli
            apache2-foreground
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_DATABASE
          value: "appdb"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "rootpassword"
        volumeMounts:
        - name: php-app-volume
          mountPath: /var/www/html
      volumes:
      - name: php-app-volume
        configMap:
          name: php-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache-service
  namespace: microservices
spec:
  selector:
    app: php-apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
